name: ddlcmm
description: A DDLC Mod Manager.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.1.2
  url_launcher: ^6.1.12
  window_manager: ^0.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/Logo.webp
    - mod/
  fonts:
      - family: Quicksand
        fonts:
          - asset: assets/fonts/Quicksand-Regular.ttf
